const env = import.meta.env;
export const APPWRITE_PROJECT_ID = env.VITE_APPWRITE_PROJECT_ID;
export const APPWRITE_DATABASE_ID = env.VITE_APPWRITE_DATABASE_ID;
export const APPWRITE_BUCKET_ID = env.VITE_APPWRITE_BUCKET_ID;
export const BACKEND_LINK = env.VITE_BACKEND_LINK